import type { Metadata } from "next";
import SessionWrapper from "@/component/SessionWrapper";
import "../styles/index.scss";
import MainHeader from "@/component/Navigation/MainHeader";
import Footer from "@/component/Footer/Footer";

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/bizz.png",
  },
};
if (process.env.NODE_ENV === "development") {
  const originalWarn = console.warn;
  console.warn = (...args) => {
    if (args[0].includes("The legacy JS API is deprecated")) {
      return;
    }
    originalWarn(...args); // 다른 경고는 계속 표시
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <title>비즈토스 현빈</title>
        <body>
          <MainHeader />
          {children}
          <Footer />
        </body>
      </html>
    </SessionWrapper>
  );
}
