import type { Metadata } from "next";
import SessionWrapper from "@/component/SessionWrapper";
import "../styles/index.scss";
import MainHeader from "@/component/Navigation/MainHeader";

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/bizz.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <title>비즈토스 현빈</title>
        <body>
          <MainHeader />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
